//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiproject8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public int College_Id { get; set; }
        public string College_Name { get; set; }
        public string College_Description { get; set; }
        public string College_Image { get; set; }
    }
}
